using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class StringSyncModel
{

    [RealtimeProperty(1, true, true)]
    public string _tring;
    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class StringSyncModel : RealtimeModel {
    public string tring {
        get {
            return _tringProperty.value;
        }
        set {
            if (_tringProperty.value == value) return;
            _tringProperty.value = value;
            InvalidateReliableLength();
            FireTringDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(StringSyncModel model, T value);
    public event PropertyChangedHandler<string> tringDidChange;
    
    public enum PropertyID : uint {
        Tring = 1,
    }
    
    #region Properties
    
    private ReliableProperty<string> _tringProperty;
    
    #endregion
    
    public StringSyncModel() : base(null) {
        _tringProperty = new ReliableProperty<string>(1, _tring);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _tringProperty.UnsubscribeCallback();
    }
    
    private void FireTringDidChange(string value) {
        try {
            tringDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _tringProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _tringProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.Tring: {
                    changed = _tringProperty.Read(stream, context);
                    if (changed) FireTringDidChange(tring);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _tring = tring;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
